name: Deploy docs to Hostinger

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**' # Only run when docs are updated
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs/package.json

      - name: Install dependencies
        working-directory: docs
        run: npm ci

      - name: Build with VitePress
        working-directory: docs
        run: npm run build

      - name: Sync files to Hostinger via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 65002 # Hostinger usually uses port 65002 for SFTP. Change to 22 if that doesn't work!
          local_path: './docs/.vitepress/dist/*'
          remote_path: '/public_html/'
          sftp_only: true
